FROM python:3.12-slim

WORKDIR /app

RUN pip install uv
RUN uv venv
COPY pyproject.toml .
RUN uv sync
RUN uv pip install --requirement pyproject.toml

COPY . .

EXPOSE 8000

CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
